### ISSUE TITLE
Difficulty when trying to setup dynamic configuration via `docker-compose.yml`

### ISSUE THREAD

**Issue by notABluesSinger** [traefik-plugins/traefik-jwt-plugin#58]
Thanks for providing this plugin... I think this is probably my issues, but wondering if I could get some help.

I'm trying to set the JWT auth up in Traefik while using docker-compose (I've copied the relevant sections from my compose file below)

I'm struggling converting the dynamic configuration into the labels format.
```
version: '3'

services:
  traefik:
    image: traefik:latest
    command:
      - --providers.docker
      - --api
      - --log.level=DEBUG
      ...
      - --experimental.plugins.traefik-jwt-plugin.moduleName=github.com/team-carepay/traefik-jwt-plugin
      - --experimental.plugins.traefik-jwt-plugin.version=v0.6.0
```
I've tried several variations of the below to align with the examples provided and I get an error that the configuration is invalid.
```
    labels:
      - traefik.http.middlewares.my-traefik-jwt-plugin.plugin.traefik-jwt-plugin.Keys="CONTENTS OF .PUB FILE"
```
However, if I use the below, everything works, but _every_ provided jwt will work, regardless of where it was generated.
```
    labels:
      - traefik.http.middlewares.my-traefik-jwt-plugin.plugin.traefik-jwt-plugin="ANY VALUE AT ALL"
```

Any ideas?

Thanks
