### ISSUE TITLE
Plugin fetches jwkEndpoints a lot of times over a short period of time

### ISSUE THREAD

**Issue by cmartell-at-ocp** [traefik-plugins/traefik-jwt-plugin#67]
Hello,

We're running into an issue where the plugin will start fetching jwkEndpoints a lot, as opposed to every 15 minutes as I'd expect based on the source code in jwt.go.

I initially discovered this through tracing, and confirmed it by enabling DEBUG level logs in Traefik.

This is how we are configuring the Middleware (headers and namespace cleaned for simplicity):

``` yaml
spec:
  plugin:
    jwt:
      JwtHeaders:
        x-head-aud: aud
        x-head-exp: exp
        x-head-sub: sub
      Keys:
        - http://http.<namespace>/oidc/v1/jwks
      PayloadFields:
        - sub
        - exp
        - aud
      Required: true
```

Checking the Debug log, I noticed "time" is zeroed, and ip, port, url and sub are empty. I wonder if the plugin doesn't really support internal services as key provicers?

Note that everything else seems to work fine with the Middleware, but the constant fetching of the jwks seems to get worse the longer we let the traefik pod run. Once we restart the pod, it seems to go back down to every 15 minutes for a little while before it starts querying jwks non-stop.

[traefik.log](https://github.com/traefik-plugins/traefik-jwt-plugin/files/14675700/traefik.log)

**Comment by eshepelyuk** [comment]
Hello 
As a maintainer I am not using this functionality. 
Are you willing to provide a PR or an investigation ?

**Comment by cmartell-at-ocp** [comment]
Willing to assist in whichever way I can.

This is the part of the code that I'd expect will keep the keys "cached" for 15 minutes: https://github.com/traefik-plugins/traefik-jwt-plugin/blob/main/jwt.go#L198-L203

But I'm not sure how Traefik handle plugins. Does it load a copy of the plugin every new request? Is the plugin reused across requests? I wonder if it is simply a matter of old running plugins not being "cleaned up" after a request is completed.

**Comment by eshepelyuk** [comment]
> Willing to assist in whichever way I can.
> 
> This is the part of the code that I'd expect will keep the keys "cached" for 15 minutes: https://github.com/traefik-plugins/traefik-jwt-plugin/blob/main/jwt.go#L198-L203
> 
> But I'm not sure how Traefik handle plugins. Does it load a copy of the plugin every new request? Is the plugin reused across requests? I wonder if it is simply a matter of old running plugins not being "cleaned up" after a request is completed. 

it may be the case. I've been fixing one cashing issue in the other plugin.
Since traefik docs doesn't supply proper explanation - it's only matter of experiments.

are you able to research this?

**Comment by spezifanta** [comment]
Hi

We ran into a similar situation. We use a lot of dynamic configurations ([file provider](https://doc.traefik.io/traefik/providers/file/)) for each of our customers. We deploy them all at the same time.
This is from our **daily** access.log:

```
[root@proxy logs]# grep "/certs" access.log | jq .'RequestPath' | cut -d'/' -f3 | sort | uniq -c
   8021 customer1-prod
  20358 customer2-prod
  20358 customer3-prod
  20360 customer4-prod
  20358 customer5-prod
  ...
  20359 customerX-prod
  123 other-service
  ```
    
  These are requests to the URL configured in the `key` section of the plugin (see below), grouped by customer name. Interestingly, `customer1-prod` is one of our newest customers.

We suspect that this high number of requests could be caused by the dynamic files, spawning a new BackgroundRefresh() routine every time the config changes/reloads. The `other-service` does not get deployed that often, therefore it's count is smaller. We do not restart Traefik after our deployments.

Current middleware config:

```yaml
http:
  middlewares:
    # Validate access token using Traefik Plugin.
    web-token:
      plugin:
        token:
          PayloadFields: ["exp", "sub", "sid", "iss"]
          Required: true
          JwtCookieKey: token
          JwtQueryKey: token
          Keys:
            - https://example.com/realms/customer1-prod/protocol/openid-connect/certs
```


Mabye this helps.
